name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.0.12
  - seaborn=0.11.1
  - pandas=1.5.3
  - pip=20.3.3
  - pandas-profiling=3.6.2
  - pyarrow=2.0
  - python=3.8
  - pip:
      - wandb==0.13.9